### ISSUE TITLE
Fix: localhost에서는 websocket 통신이 잘 되는데 remote 서버에서는 안되는 현상 수정

### ISSUE THREAD

**Issue by vimkim** [boostcampwm2023/web15-BaekjoonRooms#134]
## 👨‍🔧 버그 수정 사항

![image](https://github.com/boostcampwm2023/web15-BaekjoonRooms/assets/18080546/4d6c800a-2182-4459-9292-9234163924d9)

## 📖 참고 사항

https://www.piesocket.com/websocket-tester
https://socket.io/docs/v4/handling-cors/
https://socket.io/docs/v4/troubleshooting-connection-issues/#problem-the-socket-is-not-able-to-connect

**Comment by dqgthb** [comment]
해결...!!

![image](https://github.com/boostcampwm2023/web15-BaekjoonRooms/assets/18080546/d5edd519-ee45-4a9e-95ac-72c360523f21)

![image](https://github.com/boostcampwm2023/web15-BaekjoonRooms/assets/18080546/3dc46dfa-15e1-4b3f-8d31-69117fd8ca79)
