### ISSUE TITLE
Fix: QueryFailedError: Field 'username' doesn't have a default value

### ISSUE THREAD

**Issue by vimkim** [boostcampwm2023/web15-BaekjoonRooms#192]
<img width="797" alt="image" src="https://github.com/boostcampwm2023/web15-BaekjoonRooms/assets/18080546/f57813da-a2d7-41d4-9db1-806670ca64d4">

QueryError

**Comment by dqgthb** [comment]
Room에서 cascade: true, nullable: true 를 지워주니까 해결...?

**Comment by dqgthb** [comment]
lazy relation, promise 관련 버그입니다.
this.repository.create() 로는 생성이 안 되고,
this.repository.save(
{ code, host: Promise.resolve(user) });

이걸로만 생성이 됩니다.

https://github.com/typeorm/typeorm/issues/2276
https://github.com/typeorm/typeorm/issues/10530

2년전, 그리고 지난 주에도 계속 이슈가 되어온 버그?인 듯 합니다.
