### ISSUE TITLE
Feat: Room Refactoring

### ISSUE THREAD

**Issue by Lukaid-dev** [boostcampwm2023/web15-BaekjoonRooms#199]
## 💎 개발할 기능

오늘 게임 시작 등 소켓연결 확인

이때 앞단 코드 중 Room의 하위 컴포넌트들과 이들의 props들이 너무 꼬여있어서 관리가 힘든 이슈가 있음

이를 해결하기 위해 Room의 상단에 RoomContextProvider를 만들 예정

**Comment by glowisn** [comment]
👍👍
